### ISSUE TITLE
disable power when enable filters or thermostat - esphome

### ISSUE THREAD

**Issue by Marcin685** [jnsbyr/esp8266-intexsbh20#49]
Hello
I install from https://esphome-intexsbh20.piitaya.fr/en and add to my Home Assistant. 

-------------------------------------
```
substitutions:
  name: intex-pure-spa-297627
  friendly_name: Intex Pure Spa 297627
packages:
  piitaya.esphome-intex-pure-spa: github://piitaya/esphome-intexsbh20/intex-pure-spa.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: **************************************
ota:
  platform: esphome
  password: "******************"
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```
-------------------------------------------------

Bubble switch and water temperature works ok. When i switch to ON, bubble pomp works good.
When i switch Thermostat, set temperature and heat, power switch go back to OFF. The sound of the pump is heard for a moment.
What is wrong? I built it according to the diagram, I have an independent 5V power supply. There are errors in diagnostics, but I don't know what type and what causes them.

![image](https://github.com/user-attachments/assets/358a80b8-5e4d-43df-9b2f-4416157d0f6f)
![image](https://github.com/user-attachments/assets/0f639a53-db2e-4c33-ae96-0467b0ebeb9a)

Regards
Marcin
